on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "22"

      - run: npm i
      - run: npm test
      - run: npm run bundle
      - run: npm run generate-types

      - uses: JS-DevTools/npm-publish@v3
        with:
          access: public
          token: ${{ secrets.NPM_AUTH_TOKEN }}
